// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	UserID    uuid.UUID
	UserName  string
	Password  []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}
